apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-dotnet-webapi
  labels:
    name: kubernetes-dotnet-webapi
spec:
  selector:
    matchLabels:
      app: kubernetes-dotnet-webapi
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-dotnet-webapi
    spec:
      containers:
        - name: kubernetes-dotnet-webapi
          image: "kubernetesdotnetwebapi"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
